In [1]:
import pandas as pd
import glob
import os
import numpy as np

import tensorflow as tf
from tensorflow import keras

Read input files as a list.

In [2]:
df = pd.read_csv("cazy_df.csv",index_col=0)

In [3]:
df_names = df.columns[:-1]

In [4]:
d = pd.DataFrame( data={"classes" : df_names})

In [5]:
t = glob.glob("test_files/*.tsv") # replace this with your input files

In [6]:
classes = ["saprotroph","necrotroph","hemibiotroph","biotroph"]

Parse input files to a pandas dataframe where the rows correspond to each file and the columns to all annotations.

In [7]:
l=[]
for i in t:
    r = pd.read_csv(i,"\t")
    s = r[r["#ofTools"]==3].groupby("DIAMOND").sum()
    d1 = d.merge(s.reset_index(),how="left",left_on="classes",right_on="DIAMOND").iloc[:,[0,2]]
    d1.columns = ["classes",i.split("/")[1]]
    d1 = d1.transpose()
    d1.columns = d1.iloc[0]
    d1 = d1[1:]
    l.append(d1)

In [8]:
Xt= pd.concat(l,axis=0)

In [9]:
# Xt = Xt.transpose()
Xt = Xt.replace(np.nan,0).astype(int)

In [10]:
Xt

classes                      AA0  AA1  AA1+CBM1  ...  PL9_1  PL9_2  PL9_3
Albugo_laibachii.ENA1_B.tsv    0    3         0  ...      0      0      0
GCA_000002495.2.tsv            3    3         0  ...      0      0      0
GCA_000002525.1.tsv            0    3         0  ...      0      0      0

[3 rows x 593 columns]

Read model.

In [11]:
model = tf.keras.models.load_model('lspred_6_6_21.h5')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 593)               352242    
_________________________________________________________________
dense_1 (Dense)              (None, 512)               304128    
_________________________________________________________________
dense_2 (Dense)              (None, 480)               246240    
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 1924      
Total params: 904,534
Trainable params: 904,534
Non-trainable params: 0
_________________________________________________________________


Run predict method on the model to get probabilities for all output classes.

In [13]:
pred = model.predict(Xt)

In [14]:
print(classes)
print(pred)

['saprotroph', 'necrotroph', 'hemibiotroph', 'biotroph']
[[1.4210328e-11 1.3124628e-06 1.1535585e-15 9.9999869e-01]
 [1.2182017e-16 8.3954603e-19 1.0000000e+00 6.5379519e-16]
 [1.0000000e+00 6.6392282e-19 5.5925851e-18 5.2694670e-13]]


Format probabilities in a dataframe.

In [15]:
p = pd.DataFrame(pred)
p.columns = classes
p.index = Xt.index
p

saprotroph  ...      biotroph
Albugo_laibachii.ENA1_B.tsv  1.421033e-11  ...  9.999987e-01
GCA_000002495.2.tsv          1.218202e-16  ...  6.537952e-16
GCA_000002525.1.tsv          1.000000e+00  ...  5.269467e-13

[3 rows x 4 columns]